### ISSUE TITLE
mapping between gene catalogue and MAG genes

### ISSUE THREAD

**Issue by tkosciolek** [microbiome-immunity-project/metagenomome_assembly#2]
You could create a Python script that links the non-redundant gene catalogue back to contigs, and then back to MAGs. It could be a mapping table.

**Comment by tkosciolek** [comment]
#4ckvnw

**Comment by Marysteph** [comment]
Cool. I will do that

**Comment by tkosciolek** [comment]
for now we just have access to cluster centroids, because we would need the CD-HIT log. Tommi will update
